.\"                                      Hey, EMACS: -*- nroff -*-
.\" Первый параметр, NAME, должен быть заглавными.
. \ "Второй параметр, РАЗДЕЛ, должен быть от 1 до 8, возможно w/ subsection
.\" допустимы другие параметры: see man(7), man(1)
.TH LGC-PG 1 "October  07, 2012"
.\" Пожалуйста, измените эту дату всякий раз, когда редактируете справочную страницу.
.\"
.\" Некоторые макросы roff, для справки:
.\" .nh        отключить перенос
.\" .hy        включить перенос
.\" .ad l      левое выравнивание
.\" .ad b      выровнять по левому и правому краям
.\" .nf        отключить заполнение
.\" .fi        разрешить заполнение
.\" .br        вставить разрыв строки
.\" .sp <n>    вставить n + 1 пустую строку
.\" для макросов, специфичных для man-страницы, см. man(7)
.SH NAME
lgc-pg \- Инструмент конвертера для оригинального Panzer General\*R Data Files
.SH SYNOPSIS
.B lgc-pg
[\-s SOURCE] [\-d DEST] [\-\-defpal] [\-\-custom] [\-n NAME] [\-i ID] [\-t TACICONS]
.br
.SH DESCRIPTION
LGC-PG - это простой инструмент для преобразования оригинального Panzer General\*R Data into LGeneral Data Files. 
.SH OPTIONS
.TP
.B \-s
Вам всегда нужно указывать исходный каталог (который содержит
исходные данные или индивидуальный сценарий).
.TP
.B \-d
Это указывает путь назначения, который содержит структуру данных LGeneral. (usually /usr/share/games/lgeneral)
.TP
.B \-\-defpal
Это необязательно и заставляет всю графику PG использовать значение по умолчанию
палитра. Обычно вам это не нужно, но если по индивидуальному сценарию вы
преобразованный предлагает странную графику, это может быть связано с повреждением
палитра и палитра по умолчанию могут обеспечить лучшие результаты.
.TP
.B \-\-custom
Если вы конвертируете собственный сценарий, вам следует добавить этот и следующие параметры.
.TP
.B \-n
Это имя файла сценария и заголовок по умолчанию.
.TP
.B \-i <ID>
Это <ID> в имени исходного файла (игра <ID> .scn). Если вы не укажете идентификатор, по умолчанию будет O.
.TP
.B \-t <TACICONS>
Если задействованы пользовательские тактические значки (сценарий предлагает TACICONS.SHP), это имя графического файла.
Если этот параметр не указан, по умолчанию используется <ИМЯ> .bmp.
.SH EXAMPLES
.TP
1) Преобразует все данные с CD-ROM
.TP
lgc-pg \-s /mnt/windows/DAT \-d /usr/share/games/lgeneral
.TP
2) Преобразует индивидуальный сценарий
.TP
lgc-pg \-s /home/jones/newstuff/dunk \-d /usr/share/games/lgeneral \-\-custom \-n Dunkirk \-i 44

